### ISSUE TITLE
Upgrade package to the newly released 1.1.1

### ISSUE THREAD

**Issue by sinkingpoint** [iozag/chocolatey-packages#8]
The newly released [v1.1.1](https://github.com/github/git-lfs/releases/tag/v1.1.1) fixes a number of bugs. in particular, the installer now works properly in silent mode as per https://github.com/github/git-lfs/issues/941 . This package should be updated to install this new version.

**Comment by pascalberger** [comment]
@sinkingpoint Thank you for the PR!

Updated packages for git-lfs 1.1.1 were submitted to the chocolatey gallery and awaiting moderation.

**Comment by pascalberger** [comment]
@sinkingpoint FYI the updated package is now approved on the Chocolatey gallery
